name: 'Label Checker'

# labels changed
on:
  pull_request:
    branches:
      - '**'
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read
  checks: write

jobs:
  DoNotMerge:
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@v3.3
        id: checkLabel
        with:
          hasNone: bug, question
          githubToken: ${{ secrets.GITHUB_TOKEN }}
  BLOCKWHENHELPWANTED:
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@v3.3
        id: checkLabel
        with:
          hasNone: help wanted
          hasAll: help wanted, question
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          