name: 'Label Checker'

# labels changed
on:
  pull_request:
    branches:
      - '**'
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: write

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint PR Label
      id: check_label
      uses: actions/github-script@v6
      with:
        script: |
          if (!github.event.pull_request.labels || github.event.pull_request.labels.length === 0) {
            core.setOutput("error_message", "최소 한 개의 Label이 있어야 합니다.")
            throw new Error("최소 한 개의 Label이 있어야 합니다.")
          }

          if(github.event.pull_request.labels.some(label => label.name === 'invalid')) {
            core.setFailed("error_message", "invalid Label이 있을 경우 PR을 Merge할 수 없습니다.")
            throw new Error("invalid Label이 있을 경우 PR을 Merge할 수 없습니다.")
          }

          if(github.event.pull_request.labels.some(label => label.name === 'bug') && !github.event.pull_request.labels.some(label => label.name === 'duplicate')) {
            core.setFailed("error_message", "bug Label이 있을 경우 PR을 Merge할 수 없습니다. 단, duplicate Label이 함께 있을 경우 Merge 가능합니다.")
            throw new Error("bug Label이 있을 경우 PR을 Merge할 수 없습니다. 단, duplicate Label이 함께 있을 경우 Merge 가능합니다.")
          }
    - name: catch error and show label rule
      uses: marocchino/sticky-pull-request-comment@v2
      if: always() && (steps.check_label.outputs.error_message != null)
      with:
        header: label-lint-error
        message: |
          에러: ${{ steps.check_label.outputs.error_message }}}

          Label Tag는 다음과 같은 정책을 가지고 있습니다.

          - 최소한 하나의 Label이 있어야 합니다.
          - invalid Label이 있을 경우 PR을 Merge할 수 없습니다.
          - bug Label이 있을 경우 PR을 Merge할 수 없습니다.
          - 단, duplicate Label이 함께 있을 경우 Merge 가능합니다.

      # Delete a previous comment when the issue has been resolved
    - if: ${{ steps.check_abel.outputs.error_message == null }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: label-lint-error
        delete: true
