name: 'Label Checker'

# labels changed
on:
  pull_request:
    branches:
      - '**'
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read
  checks: write

jobs:
  PASS:
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@v3.3
        id: checkLabel
        with:
          hasSome: question, documentation
          githubToken: ${{ secrets.GITHUB_TOKEN }}
  DoNotMerge:
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@v3.3
        id: checkLabel
        with:
          hasNone: bug, question
          githubToken: ${{ secrets.GITHUB_TOKEN }}
# if only help wanted tag exists  
# but if there are help wanted tag and question tag, it will pass
# hasSome: Comma separated list of labels, PR needs at least of them
# hasAll: Comma separated list of labels, PR needs all of them
# hasNone: Comma separated list of labels, PR must not have any of them
# hasNotAll: Comma separated list of labels, PR must not have all of them
  BLOCKWHENHELPWANTED:
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@v3.3
        id: checkLabel
        with:
          hasSome: help wanted
          hasNone: question
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          