name: 'Label Checker'

# labels changed
on:
  pull_request:
    branches:
      - '**'
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read
  checks: write

jobs:
  Do_not_merge-check:
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@v3.3
        id: checkLabel
        with:
          hasNone: enhancement, bug, question
          githubToken: ${{ secrets.GITHUB_TOKEN }}
  # main:
  #   name: Block PR when label is "do not merge" or "in review"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: marocchino/sticky-pull-request-comment@v2
  #       # When the previous steps fails, the workflow would stop. By adding this
  #       # condition you can continue the execution with the populated error message.
  #       if: always() && (steps.lint_pr_title.outputs.error_message != null)
  #       with:
  #         header: pr-title-lint-error
  #         message: |
  #           subject는 PR의 내용을 간략하게 설명해주세요.

  #     # Delete a previous comment when the issue has been resolved
  #     - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
  #       uses: marocchino/sticky-pull-request-comment@v2
  #       with:
  #         header: pr-title-lint-error
  #         delete: true
